import type { Metadata } from 'next'
import { createClient } from "@/supabase/utils/server";
import { cookies } from "next/headers";
import './style/globals.css'
import { Toaster } from "@/components/ui/sonner"
import Menu from '@/components/menu'
import { redirect } from 'next/navigation'
import { CategoryType } from '@/lib/types'

export const metadata: Metadata = {
  title: 'Harry Graphics',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const supabase = createClient(cookies());

  /**** get categories ****/
  const categoriesRes = await supabase.from('categories').select().order('updated_at', { ascending: false });;
  if (categoriesRes.error || !categoriesRes.data) {
    console.log(categoriesRes.error)
  }
  const categories: CategoryType[] = categoriesRes.data || []

  /**** get user data ****/
  const { data, error } = await supabase.auth.getSession()

  const userRes = await supabase.from('users').select().eq('id', data.session?.user.id).single();
  if (userRes.error || !userRes.data) {
    console.log(userRes.error)
  }

  return (
    <html lang="en">
      <body>
        <script>0</script>
        <Menu categories={categories} user={userRes.data}/>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
