import type { Metadata } from 'next'
import './style/globals.css'
import Menu from '@/components/menu'
import { Toaster } from '@/components/ui/sonner';
import { getCategories, getUser } from '@/lib/queries';

export const metadata: Metadata = {
  title: 'Harry Graphics',
  description: 'Generated by create next app',
}

export const revalidate = 3600;
export default async function RootLayout({ children, }: {
  children: React.ReactNode
}) {
  const categories=await getCategories();
  const user=await getUser();

  return (
    <html lang="en">
      <body>
        <script>0</script>
        <Menu categories={categories} user={user}/>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
